Added a smart navigation method by direction, refactoring
NoriginMedia/react-spatial-navigation pull request #36
Opened 2019-09-11 23:30 UTC by alfimois

Hi! I fixed that issue https://github.com/NoriginMedia/react-spatial-navigation/issues/34.
Also, I added an example of navigation by wheel events.

2019-09-12 09:33 UTC, asgvard requested changes
Hi,
Thanks for your PR. It's a good functionality to have in case you need some more custom ways to trigger directional navigation apart from default arrow keys.
I've left some comments, but basically it's 2 main things:
1) Please rename the method to just `navigateByDirection`, because "smart" word was just used internally.
2) Please do not include any code style or refactoring changes in the feature or Fixes PRs, to keep the PR scope clean.
Plus some other small changes that you can find in comments.

Thanks

2019-09-12 09:33 UTC, asgvard commented on CHANGELOG.md
> +### Fixed
New functionality should be in "Added" instead of "Fixed"

2019-09-12 09:33 UTC, asgvard commented on README.md
> +smartNavigateByDirection('top'); // The focus is moved to top
```suggestion
smartNavigateByDirection('up'); // The focus is moved to top
```

Up/Down naming is better for directions, Top/Bottom - for vertical positioning.

2019-09-12 09:33 UTC, asgvard commented on src/App.js
> +import {shuffle, throttle} from 'lodash';
We are not using import from lodash for a reason, because it includes the whole "lodash" library in the bundle. In this case we have to use "babel-lodash" plugin, which we don't want to include since it will require to create a babel config (which we also don't want to include to keep it simple).

2019-09-12 09:33 UTC, asgvard commented on src/App.js
> +    return (
Please don't change code style or remove anything that is not related to your specific feature or fix. This console logs are there to make it easier to debug the sandbox App when we need it.

2019-09-12 09:33 UTC, asgvard commented on src/spatialNavigation.js
> +  smartNavigateByDirection(direction) {
As Antonio mentioned, let's rename it to something like `navigateByDirection`, so just to remove "smart" since it's an internal name (which maybe doesn't even make sense, but this is how it was historically, because it's smart :) )

2019-09-12 09:34 UTC, asgvard commented on src/spatialNavigation.js
> +  smartNavigateByDirection(direction) {
And also please rename it in the README in this case. Thanks

2019-09-12 10:30 UTC, yarikleto commented on README.md
> +smartNavigateByDirection('top'); // The focus is moved to top
Fixed

2019-09-12 10:31 UTC, yarikleto commented on src/App.js
> +import {shuffle, throttle} from 'lodash';
Fixed

2019-09-12 10:31 UTC, yarikleto commented on src/App.js
> +    return (
Fixed

2019-09-12 10:31 UTC, yarikleto commented on src/spatialNavigation.js
> +  smartNavigateByDirection(direction) {
Fixed

2019-09-16 08:53 UTC, alfimois commented
Hi, could you confirm the PR?

2019-09-16 09:49 UTC, asgvard requested changes
Hi, sorry, I was busy last days and didn't have time to review.
As both me and @salvan13 mentioned before, please **do not** include any changes that are not relevant to your feature. It makes it hard and time consuming to review because for every change where you just adding new lines or move things around we need to actually try to understand whether it's a change required for the feature or you just wanted to make code look prettier (which is good of course). But for example we got used to render components on the same line as opening/closing parenthesis:
```jsx
return (<Component>
</Component);
```
We don't have explicit ESLint rule for this, but there is no point in changing one format to another if it's not requited for your feature in PR.
If everyone will start to introduce 100 lines of codestyle changes and 2 lines of actual feature changes, PRs would be huge and it will just take longer to review.

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +      <TouchableOpacity
Codestyle change

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    const rootStyle = [styles.menu, this.props.hasFocusedChild ? styles.menuFocused : null];
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    return (
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    return (
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    return (
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    this.scrollRef.scrollTo({x});
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    return (
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    return (
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/App.js
> +    return (
Codestyle change / refactoring

2019-09-16 09:49 UTC, asgvard commented on src/spatialNavigation.js
> +        event.preventDefault();
Codestyle change / refactoring

2019-09-17 08:28 UTC, asgvard approved these changes
Thanks!

2019-09-17 08:28 UTC, merged

2019-09-17 09:02 UTC, alfimois commented
Oh thanks)