remove stopPropagation
NoriginMedia/react-spatial-navigation pull request #74
Opened 2020-09-15 07:52 UTC by jbbpatel94

it was preventing event from propagating to outside to parent view.

2020-09-15 07:54 UTC, asgvard reviewed
The reason for stopPropagation (if I remember correctly) was that if you are inside a scrolling list and press arrow keys, it was propagating up and also performing scrolling, which was an undesirable side effect. We should think on how to make it configurable if this is really necessary to get this event propagated.

2020-09-15 08:00 UTC, jbbpatel94 commented
I am using this inside the webview, not getting any event there

2020-09-15 10:08 UTC, predikament commented
Hello @jbbpatel94. Thanks for opening a PR.

> I am using this inside the android webview, not getting any event in android.

Could you please elaborate a bit more on how you've integrated the library and what the problem is that you are trying to solve?

Just opening a pull-request and removing a function, with a one sentence description is not really sufficient for anyone to make an educated decision on if this is indeed a change that makes sense to introduce.

> I think stopPropagation is preventing

From what I gather from your comments you don't entirely understand how or why `stopPropagation` works, so I would recommend reading some documentation on it first:
- [Event API `stopPropagation`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation)
- [Some general documentation for how events ordering / bubbling works](https://www.quirksmode.org/js/events_order.html)

Once you have done so, you can link our library and try making your changes in the source of it to see if:
- The change you are proposing fixes your problem
- The change you are proposing introduces any other issues

Thanks.

2020-09-15 10:24 UTC, predikament requested changes
Hello @jbbpatel94. Thanks for opening a PR.

> I am using this inside the android webview, not getting any event in android.

Could you please elaborate a bit more on how you've integrated the library and what the problem is that you are trying to solve?

Just opening a pull-request and removing a function, with a one sentence description is not really sufficient for anyone to make an educated decision on if this is indeed a change that makes sense to introduce.

> I think stopPropagation is preventing

From what I gather from your comments you don't entirely understand how or why `stopPropagation` works, so I would recommend reading some documentation on it first:
- [Event API `stopPropagation`](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation)
- [Some general documentation for how events ordering / bubbling works](https://www.quirksmode.org/js/events_order.html)

Once you have done so, you can link our library and try making your changes in the source of it to see if:
- The change you are proposing fixes your problem
- The change you are proposing introduces any other issues

As to why it is called inside this library, that was answered by @asgvard above - To avoid side-effects like scrolling of views, etc.

If I were you, I would try out these changes locally and propose f.ex. an option that can be used to toggle ON or OFF the stopping of the event propagation, as that would mean existing users of the library would see no differences, whilst you would be able to get the events you needed by enabling that option.

Thanks,
@predikament.

2020-10-28 18:20 UTC, predikament commented
Closing PR due to inactivity.

2020-10-28 18:20 UTC, closed without merging